### ISSUE TITLE
Notification of creation of public gists

### ISSUE THREAD

**Issue by zmully** [mapbox/patrol-rules-github#1]
From @alulsh:

Github-bot should have a rule that audits the creation of public Gists by team members and screens for potentially sensitive information. For example, AWS secret keys, secret access tokens, financial or sales information.

This rule would run as often as possible - either every 5 minutes (Lambda scheduling limitation) or ideally would use push notifications (webhook + SNS set up?).

Sensitive information and terms would be stored in a dictionary. If a public Gist contains a dictionary it would fire off an alert to Pager Duty. Everything else would be captured in a daily email of new public Gists that day as another control since the dictionary will not catch all examples of sensitive information, especially initially.

**Comment by alulsh** [comment]
We wrote a separate application that does this that we will open source eventually 🎉 .
